server:
  port: 8081
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wwy-pms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: pms
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    async-init: true
    initial-size: 5
    min-idle: 5
    max-wait: 60000
    max-active: 20
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/sms/*.xml

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: 商品管理系统接口列表
  try-host: http://localhost:${server.port}
